FROM pravsingh/hygieia-gitlab-scm-collector

ENV MONGO_PORT tcp://devops-hygieiadb:27017

ENV HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE hygieia

ENV MONGODB_HOST devops-hygieiadb

ENV MONGODB_PORT 27017

ENV HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME admin

ENV HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD zaq12wsx

ENV GITLAB_CRON 0 0/5 * * * *

ENV GITLAB_HOST devops-gitlab

ENV GITLAB_PROTOCOL http

ENV GITLAB_PORT 80

ENV GITLAB_API_TOKEN pp79nFihHdAfMkssyqh3

ENV GITLAB_API_VERSION 4




